Run locally with docker compose and add unit tests
TheTreasureMap/gwtm pull request #64
Opened 2024-12-17 14:41 UTC by sfoale

This PR does two main things:
1. Adds quite a few unit tests for testing the logic in the api, mocking out the database calls.
2. Adds a docker compose file that can spin up the application and its dependencies including the database for ease of  local testing.

2024-12-17 14:42 UTC, sfoale commented on src/api_v1.py
> +		return False, 'graceid is required'
Common logic extracted

2024-12-17 14:43 UTC, sfoale commented on src/function.py
> -    return rot_footprint
Not used anywhere.

2024-12-17 14:45 UTC, sfoale commented on src/models.py
> +
This is used in the docker-compose to create the database tables.

2025-01-28 17:35 UTC, swyatt7 requested changes
Hi Steve,

Again, I really appreciate you taking the time to go through this code. 

There is a lot I'd like to do to make this codebase easier to read and just split it out it a more modular fashion. But that will take much design and discussion with the team. I believe what you've done here is a step in the right direction, and I welcome it. I have not issues with your formatting changes in the code base, but have grown to like a certain standard with the tests I've been writing in other API codebases. Just let me know what you think with my comment on the tests.

Cheers,

-SW

2025-01-28 17:35 UTC, swyatt7 commented on tests/test_api_v1.py
Hi Scott, 

I appreciate you writing these tests and see them as a huge benefit to this project. I regret not taking the time and writing them when I started this project, but we were at the heels of innovation! I digress, I'm not going to be too pedantic but just some small requests when it comes to the tests.

Can we create a stronger folder structure here with appropriate `conftest.py` for the setups? Something like:

```
tests/
-> conftest.py #high level configurations
-> api/
   -> conftest.py # api level configurations
   -> pointing_test.py
   -> event_galaxies_test.py
   -> ... etc
-> forms/
   -> conftest.py 
   -> alerts_form_test.py 
....
```

So for now can you split out your huge test file into multiple test files that only perform tests for a single topic. One for pointings, one for event candidates, event galaxies ... etc.

I'd also ask that the tests follow a nested class based structure like so:
```
class PointingsSetup()
    self.client = async_client
    self.endpoint = "/api/v1/pointings/"
    self.post_data = {
            ...
     }
class TestPointings
   class TestPost(PointingsSetup):
      def test_should_return_200(self, )
      def test_should_do_this..(self)
   class TestGet(PointingsSetup):
   ...
```

If you need any clarity on these changes, feel free to reach out and we can chat about these on zoom or something.

2025-01-28 17:35 UTC, swyatt7 commented on src/tasks.py
I should note that celery functionality was removed, but the code that it called wasn't exactly. I'm not going to make it a request of this PR, but I'll put in an issue to remove all hints of the celery worker tasks.

2025-03-18 22:53 UTC, swyatt7 approved these changes
Sorry for just now getting around to looking at this. Lgtm :)

2025-04-18 15:43 UTC, merged